'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class GridViewPager
    
    Protected ImageButtonFirst As Global.System.Web.UI.WebControls.ImageButton
    
    Protected ImageButtonPrev As Global.System.Web.UI.WebControls.ImageButton
    
    Protected LabelPage As Global.System.Web.UI.WebControls.Label
    
    Protected TextBoxPage As Global.System.Web.UI.WebControls.TextBox
    
    Protected LabelNumberOfPages As Global.System.Web.UI.WebControls.Label
    
    Protected ImageButtonNext As Global.System.Web.UI.WebControls.ImageButton
    
    Protected ImageButtonLast As Global.System.Web.UI.WebControls.ImageButton
    
    Protected LabelRows As Global.System.Web.UI.WebControls.Label
    
    Protected DropDownListPageSize As Global.System.Web.UI.WebControls.DropDownList
End Class
