
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("5d490c65-cb3d-4362-bc05-a320e84d57aa")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("QLSVModel", "FK_classes_faculties", "faculties", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(faculty), "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType([class]), True)>
<Assembly: EdmRelationshipAttribute("QLSVModel", "FK_scores_classes", "classes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType([class]), "scores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(score), True)>
<Assembly: EdmRelationshipAttribute("QLSVModel", "FK_users_faculties", "faculties", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(faculty), "users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(user), True)>
<Assembly: EdmRelationshipAttribute("QLSVModel", "FK_users_roles", "roles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(role), "users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(user), True)>
<Assembly: EdmRelationshipAttribute("QLSVModel", "FK_scores_users", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(user), "scores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(score), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class QLSVEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new QLSVEntities object using the connection string found in the 'QLSVEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=QLSVEntities", "QLSVEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new QLSVEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "QLSVEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new QLSVEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "QLSVEntities")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property classes() As ObjectSet(Of [class])
        Get
            If (_classes Is Nothing) Then
                _classes = MyBase.CreateObjectSet(Of [class])("classes")
            End If
            Return _classes
        End Get
    End Property

    Private _classes As ObjectSet(Of [class])

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property faculties() As ObjectSet(Of faculty)
        Get
            If (_faculties Is Nothing) Then
                _faculties = MyBase.CreateObjectSet(Of faculty)("faculties")
            End If
            Return _faculties
        End Get
    End Property

    Private _faculties As ObjectSet(Of faculty)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property roles() As ObjectSet(Of role)
        Get
            If (_roles Is Nothing) Then
                _roles = MyBase.CreateObjectSet(Of role)("roles")
            End If
            Return _roles
        End Get
    End Property

    Private _roles As ObjectSet(Of role)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property scores() As ObjectSet(Of score)
        Get
            If (_scores Is Nothing) Then
                _scores = MyBase.CreateObjectSet(Of score)("scores")
            End If
            Return _scores
        End Get
    End Property

    Private _scores As ObjectSet(Of score)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property sysdiagrams() As ObjectSet(Of sysdiagram)
        Get
            If (_sysdiagrams Is Nothing) Then
                _sysdiagrams = MyBase.CreateObjectSet(Of sysdiagram)("sysdiagrams")
            End If
            Return _sysdiagrams
        End Get
    End Property

    Private _sysdiagrams As ObjectSet(Of sysdiagram)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property users() As ObjectSet(Of user)
        Get
            If (_users Is Nothing) Then
                _users = MyBase.CreateObjectSet(Of user)("users")
            End If
            Return _users
        End Get
    End Property

    Private _users As ObjectSet(Of user)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the classes EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToclasses(ByVal [class] As [class])
        MyBase.AddObject("classes", [class])
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the faculties EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTofaculties(ByVal faculty As faculty)
        MyBase.AddObject("faculties", faculty)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the roles EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToroles(ByVal role As role)
        MyBase.AddObject("roles", role)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the scores EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToscores(ByVal score As score)
        MyBase.AddObject("scores", score)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTosysdiagrams(ByVal sysdiagram As sysdiagram)
        MyBase.AddObject("sysdiagrams", sysdiagram)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddTousers(ByVal user As user)
        MyBase.AddObject("users", user)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLSVModel", Name:="class")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class [class]
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new class object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="class_name">Initial value of the class_name property.</param>
    ''' <param name="faculty_id">Initial value of the faculty_id property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createclass(id As Global.System.Int32, class_name As Global.System.String, faculty_id As Global.System.Int32, delflg As Global.System.Int32) As [class]
        Dim [class] as [class] = New [class]
        [class].id = id
        [class].class_name = class_name
        [class].faculty_id = faculty_id
        [class].delflg = delflg
        Return [class]
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property class_name() As Global.System.String
        Get
            Return _class_name
        End Get
        Set
            Onclass_nameChanging(value)
            ReportPropertyChanging("class_name")
            _class_name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("class_name")
            Onclass_nameChanged()
        End Set
    End Property

    Private _class_name As Global.System.String
    Private Partial Sub Onclass_nameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onclass_nameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property faculty_id() As Global.System.Int32
        Get
            Return _faculty_id
        End Get
        Set
            Onfaculty_idChanging(value)
            ReportPropertyChanging("faculty_id")
            _faculty_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("faculty_id")
            Onfaculty_idChanged()
        End Set
    End Property

    Private _faculty_id As Global.System.Int32
    Private Partial Sub Onfaculty_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onfaculty_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_classes_faculties", "faculties")>
    Public Property faculty() As faculty
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of faculty)("QLSVModel.FK_classes_faculties", "faculties").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of faculty)("QLSVModel.FK_classes_faculties", "faculties").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property facultyReference() As EntityReference(Of faculty)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of faculty)("QLSVModel.FK_classes_faculties", "faculties")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of faculty)("QLSVModel.FK_classes_faculties", "faculties", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_scores_classes", "scores")>
     Public Property scores() As EntityCollection(Of score)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of score)("QLSVModel.FK_scores_classes", "scores")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of score)("QLSVModel.FK_scores_classes", "scores", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLSVModel", Name:="faculty")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class faculty
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new faculty object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="faculty_name">Initial value of the faculty_name property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createfaculty(id As Global.System.Int32, faculty_name As Global.System.String, delflg As Global.System.Int32) As faculty
        Dim faculty as faculty = New faculty
        faculty.id = id
        faculty.faculty_name = faculty_name
        faculty.delflg = delflg
        Return faculty
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property faculty_name() As Global.System.String
        Get
            Return _faculty_name
        End Get
        Set
            Onfaculty_nameChanging(value)
            ReportPropertyChanging("faculty_name")
            _faculty_name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("faculty_name")
            Onfaculty_nameChanged()
        End Set
    End Property

    Private _faculty_name As Global.System.String
    Private Partial Sub Onfaculty_nameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onfaculty_nameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_classes_faculties", "classes")>
     Public Property classes() As EntityCollection(Of [class])
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of [class])("QLSVModel.FK_classes_faculties", "classes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of [class])("QLSVModel.FK_classes_faculties", "classes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_users_faculties", "users")>
     Public Property users() As EntityCollection(Of user)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of user)("QLSVModel.FK_users_faculties", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of user)("QLSVModel.FK_users_faculties", "users", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLSVModel", Name:="role")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class role
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new role object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="role_name">Initial value of the role_name property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createrole(id As Global.System.Int32, role_name As Global.System.String, delflg As Global.System.Int32) As role
        Dim role as role = New role
        role.id = id
        role.role_name = role_name
        role.delflg = delflg
        Return role
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property role_name() As Global.System.String
        Get
            Return _role_name
        End Get
        Set
            Onrole_nameChanging(value)
            ReportPropertyChanging("role_name")
            _role_name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("role_name")
            Onrole_nameChanged()
        End Set
    End Property

    Private _role_name As Global.System.String
    Private Partial Sub Onrole_nameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub Onrole_nameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_users_roles", "users")>
     Public Property users() As EntityCollection(Of user)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of user)("QLSVModel.FK_users_roles", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of user)("QLSVModel.FK_users_roles", "users", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLSVModel", Name:="score")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class score
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new score object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="student_id">Initial value of the student_id property.</param>
    ''' <param name="class_id">Initial value of the class_id property.</param>
    ''' <param name="score1">Initial value of the score1 property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    Public Shared Function Createscore(id As Global.System.Int32, student_id As Global.System.Int32, class_id As Global.System.Int32, score1 As Global.System.Double, delflg As Global.System.Int32) As score
        Dim score as score = New score
        score.id = id
        score.student_id = student_id
        score.class_id = class_id
        score.score1 = score1
        score.delflg = delflg
        Return score
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property student_id() As Global.System.Int32
        Get
            Return _student_id
        End Get
        Set
            Onstudent_idChanging(value)
            ReportPropertyChanging("student_id")
            _student_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("student_id")
            Onstudent_idChanged()
        End Set
    End Property

    Private _student_id As Global.System.Int32
    Private Partial Sub Onstudent_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onstudent_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property class_id() As Global.System.Int32
        Get
            Return _class_id
        End Get
        Set
            Onclass_idChanging(value)
            ReportPropertyChanging("class_id")
            _class_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("class_id")
            Onclass_idChanged()
        End Set
    End Property

    Private _class_id As Global.System.Int32
    Private Partial Sub Onclass_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onclass_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property score1() As Global.System.Double
        Get
            Return _score1
        End Get
        Set
            Onscore1Changing(value)
            ReportPropertyChanging("score1")
            _score1 = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("score1")
            Onscore1Changed()
        End Set
    End Property

    Private _score1 As Global.System.Double
    Private Partial Sub Onscore1Changing(value As Global.System.Double)
    End Sub

    Private Partial Sub Onscore1Changed()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_scores_classes", "classes")>
    Public Property [class]() As [class]
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLSVModel.FK_scores_classes", "classes").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLSVModel.FK_scores_classes", "classes").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property classReference() As EntityReference(Of [class])
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of [class])("QLSVModel.FK_scores_classes", "classes")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of [class])("QLSVModel.FK_scores_classes", "classes", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_scores_users", "users")>
    Public Property user() As user
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLSVModel.FK_scores_users", "users").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLSVModel.FK_scores_users", "users").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property userReference() As EntityReference(Of user)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of user)("QLSVModel.FK_scores_users", "users")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of user)("QLSVModel.FK_scores_users", "users", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLSVModel", Name:="sysdiagram")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class sysdiagram
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new sysdiagram object.
    ''' </summary>
    ''' <param name="name">Initial value of the name property.</param>
    ''' <param name="principal_id">Initial value of the principal_id property.</param>
    ''' <param name="diagram_id">Initial value of the diagram_id property.</param>
    Public Shared Function Createsysdiagram(name As Global.System.String, principal_id As Global.System.Int32, diagram_id As Global.System.Int32) As sysdiagram
        Dim sysdiagram as sysdiagram = New sysdiagram
        sysdiagram.name = name
        sysdiagram.principal_id = principal_id
        sysdiagram.diagram_id = diagram_id
        Return sysdiagram
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property name() As Global.System.String
        Get
            Return _name
        End Get
        Set
            OnnameChanging(value)
            ReportPropertyChanging("name")
            _name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("name")
            OnnameChanged()
        End Set
    End Property

    Private _name As Global.System.String
    Private Partial Sub OnnameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnnameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property principal_id() As Global.System.Int32
        Get
            Return _principal_id
        End Get
        Set
            Onprincipal_idChanging(value)
            ReportPropertyChanging("principal_id")
            _principal_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("principal_id")
            Onprincipal_idChanged()
        End Set
    End Property

    Private _principal_id As Global.System.Int32
    Private Partial Sub Onprincipal_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onprincipal_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property diagram_id() As Global.System.Int32
        Get
            Return _diagram_id
        End Get
        Set
            If (_diagram_id <> Value) Then
                Ondiagram_idChanging(value)
                ReportPropertyChanging("diagram_id")
                _diagram_id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("diagram_id")
                Ondiagram_idChanged()
            End If
        End Set
    End Property

    Private _diagram_id As Global.System.Int32
    Private Partial Sub Ondiagram_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Ondiagram_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property version() As Nullable(Of Global.System.Int32)
        Get
            Return _version
        End Get
        Set
            OnversionChanging(value)
            ReportPropertyChanging("version")
            _version = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("version")
            OnversionChanged()
        End Set
    End Property

    Private _version As Nullable(Of Global.System.Int32)
    Private Partial Sub OnversionChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnversionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property definition() As Global.System.Byte()
        Get
                Return StructuralObject.GetValidValue(_definition)
        End Get
        Set
            OndefinitionChanging(value)
            ReportPropertyChanging("definition")
            _definition = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("definition")
            OndefinitionChanged()
        End Set
    End Property

    Private _definition As Global.System.Byte()
    Private Partial Sub OndefinitionChanging(value As Global.System.Byte())
    End Sub

    Private Partial Sub OndefinitionChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="QLSVModel", Name:="user")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class user
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new user object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="username">Initial value of the username property.</param>
    ''' <param name="password">Initial value of the password property.</param>
    ''' <param name="faculty_id">Initial value of the faculty_id property.</param>
    ''' <param name="delflg">Initial value of the delflg property.</param>
    ''' <param name="role_id">Initial value of the role_id property.</param>
    Public Shared Function Createuser(id As Global.System.Int32, username As Global.System.String, password As Global.System.String, faculty_id As Global.System.Int32, delflg As Global.System.Int32, role_id As Global.System.Int32) As user
        Dim user as user = New user
        user.id = id
        user.username = username
        user.password = password
        user.faculty_id = faculty_id
        user.delflg = delflg
        user.role_id = role_id
        Return user
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property username() As Global.System.String
        Get
            Return _username
        End Get
        Set
            OnusernameChanging(value)
            ReportPropertyChanging("username")
            _username = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("username")
            OnusernameChanged()
        End Set
    End Property

    Private _username As Global.System.String
    Private Partial Sub OnusernameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnusernameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property password() As Global.System.String
        Get
            Return _password
        End Get
        Set
            OnpasswordChanging(value)
            ReportPropertyChanging("password")
            _password = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("password")
            OnpasswordChanged()
        End Set
    End Property

    Private _password As Global.System.String
    Private Partial Sub OnpasswordChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpasswordChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property faculty_id() As Global.System.Int32
        Get
            Return _faculty_id
        End Get
        Set
            Onfaculty_idChanging(value)
            ReportPropertyChanging("faculty_id")
            _faculty_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("faculty_id")
            Onfaculty_idChanged()
        End Set
    End Property

    Private _faculty_id As Global.System.Int32
    Private Partial Sub Onfaculty_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onfaculty_idChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property delflg() As Global.System.Int32
        Get
            Return _delflg
        End Get
        Set
            OndelflgChanging(value)
            ReportPropertyChanging("delflg")
            _delflg = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("delflg")
            OndelflgChanged()
        End Set
    End Property

    Private _delflg As Global.System.Int32
    Private Partial Sub OndelflgChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OndelflgChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property role_id() As Global.System.Int32
        Get
            Return _role_id
        End Get
        Set
            Onrole_idChanging(value)
            ReportPropertyChanging("role_id")
            _role_id = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("role_id")
            Onrole_idChanged()
        End Set
    End Property

    Private _role_id As Global.System.Int32
    Private Partial Sub Onrole_idChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub Onrole_idChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_users_faculties", "faculties")>
    Public Property faculty() As faculty
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of faculty)("QLSVModel.FK_users_faculties", "faculties").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of faculty)("QLSVModel.FK_users_faculties", "faculties").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property facultyReference() As EntityReference(Of faculty)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of faculty)("QLSVModel.FK_users_faculties", "faculties")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of faculty)("QLSVModel.FK_users_faculties", "faculties", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_users_roles", "roles")>
    Public Property role() As role
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of role)("QLSVModel.FK_users_roles", "roles").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of role)("QLSVModel.FK_users_roles", "roles").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property roleReference() As EntityReference(Of role)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of role)("QLSVModel.FK_users_roles", "roles")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of role)("QLSVModel.FK_users_roles", "roles", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("QLSVModel", "FK_scores_users", "scores")>
     Public Property scores() As EntityCollection(Of score)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of score)("QLSVModel.FK_scores_users", "scores")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of score)("QLSVModel.FK_scores_users", "scores", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


