'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class Enumeration_EditField
    
    Protected DropDownList1 As Global.System.Web.UI.WebControls.DropDownList
    
    Protected RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    Protected DynamicValidator1 As Global.System.Web.DynamicData.DynamicValidator
End Class
