'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class Integer_EditField
    
    Protected TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    Protected RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    Protected CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator
    
    Protected RegularExpressionValidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    Protected RangeValidator1 As Global.System.Web.UI.WebControls.RangeValidator
    
    Protected DynamicValidator1 As Global.System.Web.DynamicData.DynamicValidator
End Class
