'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class Default_EditEntityTemplate
    
    Protected EntityTemplate1 As Global.System.Web.DynamicData.EntityTemplate
    
    Protected DynamicControl As Global.System.Web.DynamicData.DynamicControl
End Class
