'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class Insert
    
    Protected headContent As Global.System.Web.UI.WebControls.Content
    
    Protected Content1 As Global.System.Web.UI.WebControls.Content
    
    Protected DynamicDataManager1 As Global.System.Web.DynamicData.DynamicDataManager
    
    Protected UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    Protected ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
    
    Protected DetailsViewValidator As Global.System.Web.DynamicData.DynamicValidator
    
    Protected FormView1 As Global.System.Web.UI.WebControls.FormView
    
    Protected DetailsDataSource As Global.System.Web.UI.WebControls.EntityDataSource
End Class
