'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30311.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Partial Public Class List
    
    Protected headContent As Global.System.Web.UI.WebControls.Content
    
    Protected Content1 As Global.System.Web.UI.WebControls.Content
    
    Protected DynamicDataManager1 As Global.System.Web.DynamicData.DynamicDataManager
    
    Protected UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    Protected ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary
    
    Protected GridViewValidator As Global.System.Web.DynamicData.DynamicValidator
    
    Protected FilterRepeater As Global.System.Web.DynamicData.QueryableFilterRepeater
    
    Protected DynamicFilter As Global.System.Web.DynamicData.DynamicFilter
    
    Protected GridView1 As Global.System.Web.UI.WebControls.GridView
    
    Protected GridDataSource As Global.System.Web.UI.WebControls.EntityDataSource
    
    Protected GridQueryExtender As Global.System.Web.UI.WebControls.QueryExtender
    
    Protected InsertHyperLink As Global.System.Web.DynamicData.DynamicHyperLink
End Class
